# Generated by Django 3.2.5 on 2022-05-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_posts_recepten'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredienten', to='api.recepten')),
            ],
        ),
    ]
